# Generated by Django 4.2.1 on 2023-05-23 18:48
import json
import os

from django.db import migrations


def load_currencies_names(apps, schema_editor):
    CurrencyName = apps.get_model("currency", "CurrencyName")

    with open(os.path.join("fixtures", "currencies_names.json")) as file:
        data = json.load(file)

        currencies = map(lambda x: CurrencyName(**x["fields"]), data)
        CurrencyName.objects.bulk_create(currencies)


def delete_currencies_names(apps, schema_editor):
    CurrencyName = apps.get_model("currency", "CurrencyName")

    with open(os.path.join("fixtures", "currencies_names.json")) as file:
        data = json.load(file)

        for item in data:
            CurrencyName.objects.filter(code=item["fields"]["code"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_currencies_names, delete_currencies_names)]
